### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by redox** [Flo-Schield-Bobby/colormix#1]
Hey @Flo-Schield-Bobby,

any chance you could add a license file? We would love to use your library :+1:

**Comment by flo-sch** [comment]
Hey !

Glad you use it, I add it right now :)

**Comment by flo-sch** [comment]
Fixed by #2 

Is it okay for you ?

**Comment by redox** [comment]
Awesome! Thanks a lot!

**Comment by flo-sch** [comment]
You're welcome :)

Do not hesitate to let me know if you appreciate it, or if you need anything !
