### ISSUE TITLE
this.setRed is not a function

### ISSUE THREAD

**Issue by ghost** [Flo-Schield-Bobby/colormix#3]
I am getting this error when including the script

**Comment by flo-sch** [comment]
Which version are you using?
Did you just include the file? Or could you tell me which methods are you calling?

**Comment by ghost** [comment]
v2

**Comment by flo-sch** [comment]
Could you please provide me a few more informations about the methods your are calling?

**Comment by ghost** [comment]
I was just defining a color with `ColorMix.Color`

**Comment by flo-sch** [comment]
I cannot really reproduce it, the following sample seems to work for me:

```
var c = new ColorMix.Color(1, 2, 3);
```

Can you tell me which browser are you working with?

**Comment by ghost** [comment]
Oh, I am sorry it was a syntax error did not pass the new statement for the class, I apologize, sorry for bothering you :(

**Comment by flo-sch** [comment]
No problem :)
